### ISSUE TITLE
unmanned 20mm autocannon research is missing

### ISSUE THREAD

**Issue by Pnoth** [Faryzal2020/DefinitelyMoreCannons#2]
![11](https://user-images.githubusercontent.com/44867757/48199531-a3ab0700-e39f-11e8-84fc-36845a6e4970.png)

steamapps\workshop\content\294100\1541884213\Defs\ResearchProjectDef.xml don't have a unmanned 20mm autocannon research part. 

i was trying to fix the "Definitely More Cannons - Turret Extension Patch" is keep crashing. after some digging, i find out there are no research part for 20mm unmanned cannons on the original mods ResearchProjectDef.xml

**Comment by Faryzal2020** [comment]
thank for the report, somehow steam uploaded the wrong version of the mod, which is shouldn't be possible because there is only one folder and i updated the mod on that folder, i zipped that folder and uploaded it to github right after i updated the steam version. sorry for the inconvenience.

anyway, i have reuploaded and rechecked the steam version, all should be good now.
